### PR TITLE
Add attention models

### PR DESCRIPTION
**Pull request by rmrao**
Adds Single-Layer and FactoredAttention models.

Some insights:
* Looks like changing regularization from standard weight decay -> GREMLIN W L2 regularization is very helpful
* LAMB w/ lr=0.01 is quite good

### CODE REVIEW

**Comment by nickbhat** [comment]
Where is `mogwai/lr_schedulers.py`? I don't see it.

**Comment by nickbhat** [comment]
Do we have any particular plans for `mogwai/models/multilayer_attention.py`? Seems a challenging model to train!

**Comment by nickbhat** [comment]
Proposed some changes, see what you think.

**Factored Attention** Switched to only using the MRF path so it closely resembled Gremlin. Implement value and output layers as direct params rather than nn.Linear layers. Switched to xavier init because I previously found it more stable to train. Should be somewhat faster.

**Attention** Add lr schedules and make interfaces more consistent with factored attention. Maybe more controversial changes: Switched to producing the (N, L, A, L, A) MRF weights from `compute_mrf_weight` and using that for forward pass as well. Considerably slower but opens door to potentially better regularization. The symmetrization here is quite expensive but not sure we can drop it.

https://github.com/nickbhat/mogwai/blob/ff22b327cfb99befbd6df8dc58af7e5a591e7217/mogwai/models/attention.py#L201

I'm also not entirely sure this is a reasonable way to regularize with (N, L, A, L, A).

https://github.com/nickbhat/mogwai/blob/1744f44d8aea7f3764d5dc9e232b160029757046/mogwai/models/attention.py#L162-L164

**Comment by rmrao** [comment]
I like the factored attention changes. I tried doing as you suggested with standard attention, unfortunately the memory cost is prohibitive for a reasonable batch size - total usage per Gremlin W matrix is `1600NL^2 bytes`, for `L = 150`, that's `36N MB`, so > 1 GB for a batch size of 32, just to store the Gremlin W matrix. You run out of memory way too quickly to train it :(

**Comment by nickbhat** [comment]
I agree the memory is rough; on my 1080Ti I hit a hard barrier of batch size 128 /:. The `(N, H, L, L)` activation maps are normally the memory bottleneck so it's worse by a factor of `1600 / num_attention_heads`, which should be pretty nontrivial for any hyperparameter choices we want.

I think the original approach you had of taking a mean over the batch to compute regularization with W is interesting, not sure if we should also add an option to do normal weight decay just so we can compare.

**Comment by nickbhat** [comment]
Ok I rewrote attention to the original forward pass and (as expected) it's much more efficient again. A few smaller things I proposed --

`compute_mrf_weight`: Only allow inputting attention maps, since we basically copy-pasted the forward pass on `src_tokens` as the other option.

`get_contacts`: use the block l2 norm of the mrf_weight as with other methods

regularization: I chose to sum attentions over batch instead of taking a mean, 

https://github.com/nickbhat/mogwai/blob/e4b058d2fa72a33810077592ecb1ff2df4bed53d/mogwai/models/attention.py#L197

since we later divide by batch size in the loss

https://github.com/nickbhat/mogwai/blob/e4b058d2fa72a33810077592ecb1ff2df4bed53d/mogwai/models/attention.py#L180-L181 

Didn't notice any initial difference, but this may merit further thought!

**Pull request merged**
